# Generated by Django 4.1.3 on 2022-11-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrazione',
            name='numeroBiglietti',
            field=models.IntegerField(default=0),
        ),
    ]
