# Generated by Django 4.1.3 on 2022-11-10 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_registrazione_numerobiglietti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrazione',
            name='numeroBiglietti',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
